name: hiddify
description: Multi-platform auto-proxy client
version: 2.0.0+2000
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Aquí van todas tus dependencias actuales
  # (mantén todas las que ya tienes)

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Aquí van todas tus dev_dependencies actuales
  # (mantén todas las que ya tienes)

# IMPORTANTE: dependency_overrides va al mismo nivel que dependencies
dependency_overrides:
  flutter_plugin_android_lifecycle: ^2.0.15

flutter:
  uses-material-design: true
  
  # Aquí va toda tu configuración de flutter actual
  # (assets, fonts, etc. - mantén todo lo que ya tienes)
