name: hiddify_next
description: "Multi-platform auto-proxy client, supporting Sing-box, X-ray, TUIC, Hysteria, Reality, Trojan, SSH etc. It's an open-source, secure and ad-free."
publish_to: 'none'
version: 2.5.7+20507

environment:
  sdk: '^3.5.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  connectivity_plus: ^6.0.5
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  share_plus: ^10.0.2
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  
  # Navigation
  go_router: ^14.2.7
  
  # UI
  flutter_animate: ^4.5.0
  sliver_tools: ^0.2.12
  gap: ^3.0.1
  
  # Networking
  dio: ^5.7.0
  dio_certificate_pinning: ^6.0.0
  
  # Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utilities
  uuid: ^4.5.0
  intl: ^0.19.0
  ffi: ^2.1.3
  
  # Logging
  logger: ^2.4.0
  
  # Platform specific
  window_manager: ^0.4.2
  tray_manager: ^0.2.3
  launch_at_startup: ^0.3.1
  protocol_handler: ^0.2.0
  
  # Mobile
  mobile_scanner: ^5.2.3
  qr_flutter: ^4.1.0
  wakelock_plus: ^1.2.8
  
  # Media
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  
  # File handling
  file_picker: ^8.1.2
  path: ^1.9.0
  
  # Native
  flutter_native_splash: ^2.4.1
  
  # Custom packages - remove flutter_leanback as it doesn't exist
  # flutter_leanback: any  # REMOVED - doesn't exist on pub.dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code generation
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  hive_generator: ^2.0.1
  
  # Testing
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/core/
    - assets/geo/
  
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
        - asset: assets/fonts/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
