name: hiddify_next
description: Multi-platform auto-proxy client for Android TV
publish_to: 'none'
version: 2.5.7+20250612

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.13.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Core dependencies
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.3
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  
  # Android TV specific dependencies
  flutter_leanback: ^0.4.0  # Android TV UI components
  tv_focus: ^1.0.0          # Better focus management for TV
  
  # UI & Navigation
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9
  flutter_animate: ^4.5.0
  gap: ^3.0.1
  
  # Platform specific
  window_manager: ^0.3.7
  tray_manager: ^0.2.0
  protocol_handler: ^0.2.0
  
  # Storage & Preferences
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Network & Proxy
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.2.1
  url_launcher: ^6.2.2
  
  # Native bridge
  flutter_rust_bridge: ^1.82.6
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/core/
    - assets/translations/
  
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
        - asset: assets/fonts/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
